language: go

go:
  - 1.7
  - 1.8
  - master

install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - go test ./...
  # get the coverage
  - echo "mode: set" > coverage-all.out
  - $(foreach pkg,$(packages),\
  - go test -coverprofile=coverage.out $(pkg);\
  - tail -n +2 coverage.out >> coverage-all.out;)
  - go tool cover -func=coverage-all.out
  # Upload the coverage report
  - goveralls -coverprofile=coverage-all.out -service=travis-ci