language: go

go:
  - 1.7
  - 1.8
  - master

install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  # Explicitly get the mainline jsonenums otherwise compilation fails on a fork
  - go get github.com/campoy/jsonenums
  -

script:
  - go test ./...
  # get all the packages
  - packages=$(go list ./... | grep -v -e /vendor/ -e /example -e /test)
  # get the coverage for all packages and combine to an overall coverage
  - 'echo "mode: set" > coverage-all.out'
  - 'for pkg in ${packages}; do \
     go test -coverprofile=coverage.out ${pkg}; \
     tail -n +2 coverage.out >> coverage-all.out;'
  - go tool cover -func=coverage-all.out
  # Upload the coverage report if the token is set
  - if [ ! -z ${COVERALLS_TOKEN} ]; then goveralls -coverprofile=coverage-all.out -service=travis-ci; fi